### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by tharaguc** [Shuta-syd/minishell#69]

**Comment by tharaguc** [comment]
echo " hello        -> abort

**Comment by tharaguc** [comment]
echo ' $HOME -> そのまま出るけどエラー出したい

**Comment by Shuta-syd** [comment]
envが効かない

**Comment by Shuta-syd** [comment]
`echo "this is $USER`quotedされてないコマンドを入力するとenv_lstがリークする

**Comment by tharaguc** [comment]
guacamoleでecho $?がSEGV

**Comment by tharaguc** [comment]
`$?`が参照されるタイミングで更新されていない。
